### ISSUE TITLE
Possibility of use of voice-engine/ec to Echo Cancel in Voip-Voip Calls

### ISSUE THREAD

**Issue by fischerdouglas** [voice-engine/ec#17]
I'm Looking for a solution to Echo Canceling on RTP Only Voip Calls.

All the solutions that I found deals with it on the conversion of Analog/TDM to RTP áudio.
But we have some serious problems with ECHO, and we want to cancel it on Passtrought Voip Call(that deals with the 4 legs of a call).

Do you think that somehow voice-engine/ec could be used/adapted to do this line echo canceling?

**Comment by xiongyihui** [comment]
The major issue of echo canceling on voip is that the delay is uncertain and is always changing.
If you can track the delay, you can use voice-engine/ec
