### ISSUE TITLE
Unable to define mic

### ISSUE THREAD

**Issue by davidw38** [voice-engine/ec#2]
Hey,
i wanted to try this echo canceller but when I try to start the program with the following:
./ec -i plughw:0 -o plughw:1 -d 200
I am getting this error:
Running... Press Ctrl+C to exit
ec: src/audio.c:62: set_params: Assertion `err >= 0' failed.

If I try starting ec using:
./ec -i plughw:1 -o plughw:1 -d 200
ec starts but the input does not work because my mic is at slot "0" and not slot "1"

How to fix this?

**Comment by xiongyihui** [comment]
Which sound card do you use?

Maybe the sound card doesn't support setting buffer size. You can try to comment the line https://github.com/voice-engine/ec/blob/master/src/audio.c#L61

**Comment by davidw38** [comment]
That fixed it!
Thank you very much...
It´s a cool project btw

Bye
