### ISSUE TITLE
Is it possible to use with other programs?

### ISSUE THREAD

**Issue by natriumlamp** [voice-engine/ec#7]
I found myself happy to find this amazing tool but I wonder if I can use it with other ALSA card using program.
I understand this runs standalone by using /tmp/ec.input and /tmp/ec.output 

but I want to feed echo cancelled sound stream as an ALSA device to other program. 

Is it possible to make a virtual ALSA card from ec.output?

**Comment by xiongyihui** [comment]
Yes, check https://github.com/voice-engine/ec#use-ec-with-alsa-plugins-as-alsa-devices
